### PR TITLE
Add support for Active Record 4.x

### PR DESCRIPTION
**Pull request by palkan**
Prior to Rails 5 `ActiveRecord::ConnectionAdapters::PostgreSQLColumn` doesn't have `#table_name` (or any other way to get the table information from the column).

Hence running `bundle exec database_consistency` fails with:

```
NoMethodError: undefined method `table_name' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x0000559375a32038>
```

This PR refactors code a little bit to pass `model` along with the `column` (thus it works for both Rails 4 and Rails 5).

Also, added `env` to `.travis.yml` to build against multiple versions and removed `Gemfile.lock`.

P.S. Thanks for the great tool!

### CODE REVIEW

**Comment by djezzzl** [comment]
Hi @palkan, thank you for your contribution!

I'll merge it ASAP, but just curious is there any other way to test different versions of `ActiveRecord` via travis? Environment variable with name `AR_VERSION` seems a bit weird for me. 

Also, why do we need a `Gemfile.local`? Is this a good practice? 

And now you duplicated `active-record` in `.gemspec` and `Gemfile`. Is it expected? 

> Thanks for the great tool!

👍 Happy to hear

**Comment by palkan** [comment]
>  is there any other way to test different versions of ActiveRecord via travis?

yeah, usually I use separate gemfiles (e.g. in https://github.com/palkan/logidze/tree/master/gemfiles).

env var is the fastest way to add multiple versions when you don't need any other deps to be different

> Also, why do we need a Gemfile.local? Is this a good practice?

I stole this practice years ago from [RuboCop](https://github.com/rubocop-hq/rubocop/blob/master/Gemfile#L22-L23) )) And I like it much better then alternative approach (e.g. `Appraisals`).

> And now you duplicated active-record in .gemspec and Gemfile. Is it expected?

That's a hack for CI)

**Comment by djezzzl** [comment]
Okay, I understand almost everything and I agree.
Could you explain a bit more why we need this hack? What will be without it?

**Comment by palkan** [comment]
> Could you explain a bit more why we need this hack? What will be without it?

Without this hack our env matrix in `.travis.yml` won't work–both builds would use the same (latest) version of `activerecord`.

Our gem specification from `Gemfile` takes precedence over `.gemspec` (or, more precisely, adds a restriction).

**Comment by djezzzl** [comment]
Okay, got it. 

Can it somehow affect projects which will use this gem? 
E.g. somebody adds this in his `Gemfile` and run `AR_VERSION="something wrong" bundle install` will it fail?

**Comment by djezzzl** [comment]
Yes, I see. 
Awesome, thank you for the participate and fast responses!

**Pull request merged**
