### PR TITLE
Add support of citext to MissingUniqueIndexChecker

### PR DESCRIPTION
**Pull request by djezzzl**

### CODE REVIEW

**Comment by pirj** [comment]
Does it make sense to revive this PR now?

**Comment by djezzzl** [comment]
@pirj, we can revive it, although, we should distinguish cases where your fix was applied from the rest. Could you please help how we can do that?

**Comment by pirj** [comment]
I'd say two things would affect the checker's decision:
1. Rails version. Depending on if the fix will be backported or not. Older versions would add `LOWER()` to queries. Newer won't.
2. presence of `LOWER()` on the uniqueness index.

So, the inspector should log an error:
a) for older Rails versions when there's *no* `LOWER()` on the index
b) for newer Rails versions when there's `LOWER()` functional specification on the index

Does this make sense, or am I missing something?

**Comment by djezzzl** [comment]
It makes total sense to me. Do we have a better way of relying on instead of the Rails version?

**Comment by djezzzl** [comment]
I'm not sure we can simply say the version is greater/lower.

**Comment by pirj** [comment]
We [depend on Active Record](https://github.com/djezzzl/database_consistency/blob/80e68e54020c5c52476d4a08d260eb5e2145fa8f/database_consistency.gemspec#L41) in runtime, so we can reasonably compare it:
```
> ActiveRecord.version > Gem::Version.new('6.0.4')
=> true
> ActiveRecord.version > Gem::Version.new('6.0.6')
=> false
```
Let's see when the fix is released to build a `uses_lower_in_uniqueness_validation_queries?` helper method correctly.

**Comment by djezzzl** [comment]
Sounds like a plan to me.

**Pull request closed without merging**
