### PR TITLE
Skip foreign key checker for different databases

### PR DESCRIPTION
**Pull request by uxxman**

### CODE REVIEW

**Comment by djezzzl** [comment]
Hey, thank you for your contribution and sorry for taking it so long! I'll review the PR today/tomorrow and merge it. Unfortunately, CI wasn't triggered for some reason, although I have it enabled for PRs from forks. 🤔

**Comment by djezzzl** [comment]
Meanwhile, feel free to add you to CHANGELOG.md, you can find some examples there 👍

**Review by djezzzl — APPROVED** [review]

**Comment by djezzzl** [comment]
Released in version 1.1.12. Please let me know if that works for you well.

**Comment by uxxman** [comment]
Thanks @djezzzl. Yes, I am running my forked version with this patch and it fixes the errors for multi db foreign keys

**Pull request merged**
